### ISSUE TITLE
Crafting Creature button bug on Creature Name

### ISSUE THREAD

**Issue by Borupirax** [godot-wildlings/Bioenfluencer#10]
If you press the crafting button 2 times while a creature is still displayed in the middle of the crafting screen, the "newest crafted creature's name" will override the "previous crafted creature's name".

Might be a String issue.

**Comment by kvonspiczak** [comment]
@ItsADogPen i think you fixed that already by disabling the crafting button after crafting is complete right? at least i cant reproduce that issue right now (button is disabled after pressing it).
reopen if you think the issue persists.
