### ISSUE TITLE
Create a News Feed which lets you "Catch Trends"

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/Bioenfluencer#3]
The player should be able to gather information about trends, which will affect the relevancy and value (aka currency) of their crafted products (genetically engineered creatures).

Make an influx of trends which the player can spot (and/or collect)

- News feed? 
  - moving hidden word puzzle?
  - catch the object (word or sprite) as it flies across the screen?
- Observe people on the streets and Bioenfluencers on their streams 
  - Tinder-style: swipe left/right (Reign)
- Both?

Optional: Create a mechanic which allows them to gather trends (Maybe they just have to spot the words in the feed. Maybe they have to actively grab the words with the mouse.)

Required: Make a mechanism where current trends are recorded, so they can affect the value of products.

**Comment by Borupirax** [comment]
Made the trend letters fall downwards.

**Comment by kvonspiczak** [comment]
should we add something like a _weight_ field on trends? like a follower count, indicating the strength of a given trend? maybe it gives you more points based on that, when you managed to catch those.

**Comment by kvonspiczak** [comment]
we might cluster the trends into some categories like : shape, color, type.
so in the rating we need you to have at least one of each type e.g

**Comment by kvonspiczak** [comment]
trends could be a custom resource

**Comment by plexsoup** [comment]
agree with everything above
