### ISSUE TITLE
Create a way to craft creatures

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/Bioenfluencer#4]
Some type of virtual genetic engineering? What does the gameplay mechanic look like?

- [x] the player can select as many body parts from the list of available parts as his budget allows him to
- [ ] see a preview of the creature ? or see creature when confirming selection with a button press
- [ ] preview: drop "staged" body parts and let the player drag them in place by dragging them on to the various fixed Position2D nodes, and let the part snap into place

**Comment by kvonspiczak** [comment]
![image](https://user-images.githubusercontent.com/2630690/56849127-04e47980-68f1-11e9-80da-6d00ac6ddead.png)

**Comment by kvonspiczak** [comment]
![image](https://user-images.githubusercontent.com/2630690/56851318-e9d43280-690d-11e9-87b6-7fa0f5004bef.png)
