### ISSUE TITLE
TrendsChart.tscn has multiple issues

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/Bioenfluencer#8]
The graph doesn't look good. It doesn't really understand reference rectangle yet.

**Comment by Borupirax** [comment]
after pressing Pass The Time 2 times. Looks like it's not producing a graph for the first two button presses?

**Comment by plexsoup** [comment]
Added a dialog box for first "pass time" click.
second click shows trend lines.

Graph still has issues though.

**Comment by plexsoup** [comment]
![biobug](https://user-images.githubusercontent.com/8674767/57068984-1da1b600-6c88-11e9-8080-3ac0a440327c.png)

[2:58 AM] JestemStefan: I just pressed "pass time""
[3:03 AM] JestemStefan: It happened everytime after I lose the game  and click restart
[3:03 AM] JestemStefan: then i click "pass time"
[3:04 AM] JestemStefan: and this bug happened every time

**Comment by plexsoup** [comment]
trends chart is a lot better now. Not perfect, but at least it's usable.
